version: "3"
services:
  backend:
    build: management-app/back-end/
    ports:
      - "8090:8090"
  ui:
    build: management-app/frontend/
    environment:
      - REACT_APP_PORT=3000
      - REACT_APP_ASTAIR_MANAGEMENT_BACKEND=http://10.154.4.28:8090
      - REACT_APP_LENGTH=4
      - REACT_APP_DURATION=1
      - CHOKIDAR_USEPOLLING=true
      - SKIP_PREFLIGHT_CHECK=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
