apiVersion: v1
kind: Service
metadata:
  name: {{ template "management_app_frontend.full_name" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "management_app_frontend.release_labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.reactAppPort }}
  selector:
    app: {{ template "management_app_frontend.full_name" . }}
