apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feedback_collector.full_name" . }}
  namespace: {{ .Values.namespace }}
data:
  application-port: {{ .Values.applicationPort | quote }}
  timezone: {{ .Values.timezone }}
