apiVersion: v1
kind: Service
metadata:
  name: {{ template "feedback_collector.full_name" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "feedback_collector.release_labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.applicationPort }}
  selector:
    app: {{ template "feedback_collector.full_name" . }}
