apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-collector
  namespace: astair
data:
  postgresql-url: ""

---

apiVersion: v1
kind: Service
metadata:
  name: feedback-collector-service
  namespace: astair
  labels:    
    app: feedback-collector
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: feedback-collector

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: feedback-collector
  labels:        
    app: feedback-collector
  namespace: astair
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: feedback-collector
  template: 
    metadata:
      labels:        
        app: feedback-collector
      annotations:
        checksum/config-map: 6naYyeOwWH6tk686aXYz5aa9ab4de5t8d9e8947c8142f135ec17140baf49b68f
    spec:
      containers:
        - image: astar.azurecr.io/astair-feedback-collector:0.0.3
          imagePullPolicy: Always
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /feedback-collector/health
              port: 5000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 6
          readinessProbe:
            httpGet:
              path: /feedback-collector/health
              port: 5000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 6
          name: feedback-collector
          ports: 
            - containerPort: 5000
          env:
            - name: TZ
              value: Europe/Istanbul
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  name: feedback-collector
                  key: postgresql-url
      imagePullSecrets:
        - name: astar-docker-registry-secret
